/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * TiDev Titanium Mobile
 * Copyright TiDev, Inc. 04/07/2022-Present
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 */
package ti.zendesk;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.TiConfig;
import org.appcelerator.titanium.TiApplication;

import zendesk.android.Zendesk;
import zendesk.messaging.android.DefaultMessagingFactory;


@Kroll.module(name = "TiZendesk", id = "ti.zendesk")
public class TiZendeskModule extends KrollModule {

    // Standard Debugging variables
    private static final String LCAT = "TiZendeskModule";
    private static final boolean DBG = TiConfig.LOGD;

    public TiZendeskModule() {
        super();
    }

    @Kroll.onAppCreate
    public static void onAppCreate(TiApplication app) {
    }

    // Methods
    @Kroll.method
    public void initialize(String key) {
        Zendesk.initialize(TiApplication.getAppCurrentActivity(),
                key,
                zendesk -> fireEvent("ready", new KrollDict()),
                error -> {
                    KrollDict kd = new KrollDict();
                    kd.put("error", error.getMessage());
                    fireEvent("error", kd);

                },
                new DefaultMessagingFactory()
        );
    }

    @Kroll.method
    public void showMessaging() {
        Zendesk.getInstance().getMessaging().showMessaging(TiApplication.getAppCurrentActivity());
    }

}

